### ISSUE TITLE
Should fake time work outside main thread if specified explicitly?

### ISSUE THREAD

**Issue by seporaitis** [simon-weber/python-libfaketime#16]
Hi,

While debugging an [issue on a different project](https://github.com/pytest-dev/pytest-xdist/issues/56) I used `python-libfaketime` and accidentally noticed the `fake_time` context manager [has an argument](https://github.com/simon-weber/python-libfaketime/blob/master/libfaketime/__init__.py#L104) `only_main_thread=True`. Curious I tried `only_main_thread=False`, but got an exception:

```
self = <libfaketime.fake_time object at 0x107308c50>

    def _should_patch_uuid(self):
        return hasattr(uuid, '_uuid_generate_time') and \
>               not self._prev_spec and \
                self._should_fake()
E       AttributeError: 'fake_time' object has no attribute '_prev_spec'
```

At first I thought it is just simply the case of `_prev_spec` missing and changed it to `getattr(self, '_prev_spec', None)`, but now, upon closer inspection of the issue, it is [only being set](https://github.com/simon-weber/python-libfaketime/blob/master/libfaketime/__init__.py#L114) when `only_main_thread=True`. 

Therefore before submitting any pull request I wonder - is this expected behavior?

**Comment by simon-weber** [comment]
Whoops, nope, that looks like a bug. I think I've only ever run with that option enabled :grin:

**Comment by jppgks** [comment]
Is there any solution found to this `_prev_spec` problem?

**Comment by simon-weber** [comment]
I think changing `self.only_main_thread and threading.current_thread...` to something like `not self.only_main_thread or threading.current_thread...` would work? _should_fake should also come before self._prev_spec in the _should_patch... chain, I think.

**Comment by jppgks** [comment]
@simon-weber: I'm running into this issue when running py.test within multiple processes using the `-n` flag.
I will try to fix it using your solution and make a pull request if it works. I'll keep you in the loop here.

**Comment by jppgks** [comment]
@simon-weber: For running py.test with the [-n flag](http://docs.pytest.org/en/latest/xdist.html) for running on multiple CPUs, setting the default value of `only_main_thread` to `False` and changing
```python
return self.only_main_thread and threading.current_thread().name == 'MainThread'
```
in the `_should_fake()` method to
```python
return not self.only_main_thread or threading.current_thread().name == 'MainThread'
```
works.
Should I make a pull request with this behavior?

**Comment by simon-weber** [comment]
Sounds good! A PR would be great.
