### ISSUE TITLE
Issue with running unittest from a bash script

### ISSUE THREAD

**Issue by shardool-freightwalla** [simon-weber/python-libfaketime#17]
Thanks for this library really helpful.

I  am running my unittest through the below command 
python -m unittest discover 

The mocking of date works perfectly this way , but if i run the same command through a bash script , the mocking doesn't happen.

**Comment by socketubs** [comment]
I think, I encounter the same bug when trying to run my tests through [Invoke](docs.pyinvoke.org).
Or maybe it's more thread related for me? (#16)

**Comment by simon-weber** [comment]
My guess is this has something to do with the re-exec and the parent process. Can you try running without a reexec as described at https://github.com/simon-weber/python-libfaketime#how-to-avoid-re-exec?

**Comment by shardool-freightwalla** [comment]
yes that worked. Thanks

**Comment by simon-weber** [comment]
Sure thing; glad it worked. @socketubs did it work for you too?

**Comment by socketubs** [comment]
@simon-weber Absolutely :smile:

**Comment by socketubs** [comment]
@simon-weber Absolutely :smile:
