### ISSUE TITLE
Carry LD_PRELOAD into subprocesses

### ISSUE THREAD

**Issue by adamchainz** [simon-weber/python-libfaketime#18]
We started using `pytest-xdist` for our tests recently. We had to do some work to make them work together in pytest-dev/pytest-xdist#56 . The main outcome is that we needed `os.environ['LD_PRELOAD']` to be set after `reexec_if_needed`, in order to carry it into the subprocess test workers. So we've ended up doing:

```py
libfaketime.reexec_if_needed()
_, env_additions = libfaketime.get_reload_information()
os.environ.update(env_additions)
```

`reexec_if_needed` could probably just do this for us. If it's a real worry that it could badly affect other usecases with subprocesses, it could be behind a flag.

**Comment by adamchainz** [comment]
Aha I just found out about the undocumented `remove_vars` flag. Setting it to `False` is all we need. Documenting that!

**Comment by simon-weber** [comment]
Sorry to hide that away! :grin:
