### ISSUE TITLE
Work as a pytest plugin

### ISSUE THREAD

**Issue by adamchainz** [simon-weber/python-libfaketime#19]
It would be trivial to work as a pytest plugin rather than mention the two lines of copy/paste that are necessary to integrate with pytest in the README. I'd be happy to add this functionality, I've written a few pytest plugins.

**Comment by simon-weber** [comment]
Sure; I'd appreciate that.

**Comment by azmeuk** [comment]
@adamchainz Are you still interested in writing such a plugin? I might tackle this if you don't :)

**Comment by adamchainz** [comment]
Go for it @azmeuk

**Comment by azmeuk** [comment]
Ok the plugin is called `pytest-libfaketime` and it lives [here](https://github.com/azmeuk/pytest-libfaketime). Issue solved?

**Comment by touilleMan** [comment]
I think this issue can be closed

**Comment by simon-weber** [comment]
👍 thanks everyone!
