### ISSUE TITLE
Replaced freezegun calls, but can't get libfaketime to work

### ISSUE THREAD

**Issue by jppgks** [simon-weber/python-libfaketime#21]
I am running tests in PyCharm. This Django project was using freezegun before, and I want to speed it up by using libfaketime.
However, after replacing freeze_time calls from freezegun with fake_time from libfaketime, the time isn't being frozen.
I'm using Linux in a Docker environment, but even after setting the environment variables using `eval $(python-libfaketime)` inside the running container, it doesn't work. Also no luck when using py.test with the `reexec_if_needed` in the `pytest_configure()` method.

Even after running `make` in the `vendor/libfaketime` directory, it doesn't work.

What am I doing wrong here?
CC @simon-weber @canassa @dvl @adamchainz @allardhoeve

**Comment by allardhoeve** [comment]
I believe PyCharm runs tests inside a Python thread. That thread might not
have the faketime preload installed.

Haven't tried running inside PyCharm before. Try running the tests from the
shell first.

**Comment by jppgks** [comment]
Hi there! Thanks for the quick reply!

Does the libfaketime C library need be installed before I can use python-libfaketime?

I’ll try running from the shell and then come back to you.

**Comment by allardhoeve** [comment]
No. Pip installs it for you.

**Comment by jppgks** [comment]
@allardhoeve: I tried running the tests from the shell using `django-admin test <test_bundle>`, but still no luck. Do you have any idea what is going wrong?

**Comment by jppgks** [comment]
@allardhoeve: Finally got it to work by setting the environment variables in the PyCharm test configuration (`Environment variables` in `Run - Edit configurations... - <own custom test configuration>`). 
Thanks for the help!

**Comment by simon-weber** [comment]
Glad you all got it figured out!
