### ISSUE TITLE
Async process testing 

### ISSUE THREAD

**Issue by shardool-freightwalla** [simon-weber/python-libfaketime#22]
I am running my unittest through a shell script
Using this to set the env : eval $(python-libfaketime)
and  this to run : exec python -m unittest discover -v

One of my functions calls async function, and the faketime is causing it loop forever.

I went through the approaches mentioned here: https://github.com/simon-weber/python-libfaketime/issues/18

But my python script is already on a different thread so can't reload the information from the main thread.
Appreciate your help here.

**Comment by shardool-freightwalla** [comment]
$ python-libfaketime
export DYLD_FORCE_FLAT_NAMESPACE="1"
export DYLD_INSERT_LIBRARIES="/Users/shardooldesai/Desktop/Freightwalla/Project/easyship/es-env/lib/python2.7/site-packages/libfaketime/vendor/libfaketime/src/libfaketime.1.dylib"
export FAKETIME_DID_REEXEC=true

**Comment by simon-weber** [comment]
Hm, I'm having some trouble understanding. It looks like you have two problems:

1. when mocked, an async function loops forever: is it possible to not mock for this test and/or mock the async function out separately? I know at venmo we had a similar problem where libfaketime deadlocked the stdlib uuid generator (https://github.com/simon-weber/python-libfaketime/pull/14), and we just had to work around it.
2. a separate thread doesn't have the environment variables set: can you give more details? What did you do, what happened, and what were you expecting to happen?

**Comment by shardool-freightwalla** [comment]
Thanks @simon-weber. Both problems are related.
(2) i was referring to the solution mentioned here https://github.com/pytest-dev/pytest-xdist/issues/56 , but my shell script calls the python test code hence cannt set the env variables.

I guess the only option for me here is to test the async function separately.

**Comment by shardool-freightwalla** [comment]
A weird inference:
The first call to the async functions with fake_time enabled causes deadlock.
I called the function without fake_time and then the subsequent calls with fake_time enables worked without any efforts.

Any reasons for this behaviour.

**Comment by simon-weber** [comment]
Sorry, I don't know. You really haven't given me enough details to work with -- I don't know anything about the specific async code you're dealing with.

**Comment by shardool-freightwalla** [comment]
I hope the below min example helps to understand and reproduce the error.
graph_example.py

    from sframe import SGraph, SFrame
    import datetime
    def degree_count_fn(src, edge, dst):

        src['degree'] += 1
        dst['degree'] += 1
        return (src, edge, dst)

    def graph_function_example():

        print 'Sframe started'
        edges = SFrame({'source': [1, 2, 3], 'dest': [3, 2, 1]})
        print 'Sframe created'
        g = SGraph()
        print 'Sgraph created'
        g = g.add_edges(edges, src_field='source', dst_field='dest')
        print 'Edges Added'
        print g.edges
        g.vertices['degree'] = 0
        print 'Calling Async function'
        g = g.triple_apply(degree_count_fn, mutated_fields=['degree'])

        print g.vertices

        today = datetime.datetime.now()

        print "Current date is : ", today
test_paths.py 

    import unittest
    from libfaketime import fake_time
    import graph_example as xyz

    fake_current_date = '2016-05-05 00:00:00'

    class PathsTest(unittest.TestCase):

        @fake_time(fake_current_date)
        def test_async(self):
            print 'Starting test async'
            xyz.graph_function_example()
    if __name__ == '__main__':
        unittest.main()

pip freeze 
appnope==0.1.0
awscli==1.6.2
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcdoc==0.12.2
boto==2.33.0
botocore==0.73.0
certifi==2015.4.28
colorama==0.2.5
contextdecorator==0.10.0
decorator==4.0.9
docutils==0.12
ipython==5.0.0
ipython-genutils==0.1.0
jmespath==0.5.0
libfaketime==0.4.1
multipledispatch==0.4.8
pathlib2==2.1.0
pexpect==4.2.0
pickleshare==0.7.3
prettytable==0.7.2
prompt-toolkit==1.0.3
ptyprocess==0.5.1
pyasn1==0.1.9
Pygments==2.1.3
python-dateutil==2.5.3
pyzmq==15.3.0
requests==2.9.1
rsa==3.1.2
SFrame==2.0.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
tornado==4.3
traitlets==4.2.2
wcwidth==0.1.7

OSX 10.11.5 python version : 2.7.11

I am running the code as 

    $eval(python-libfaketime)
    $python -m unittest test_paths -v

With fake_time it hangs while initializing the Sframe. and without it works fine.

if you add the following setup code in PathsTest , the error are different.

    def setUp(self):
        print 'Dummy Call'
        xyz.graph_function_example()

Sframe:
https://github.com/turi-code/SFrame

**Comment by simon-weber** [comment]
Great; thanks for the example.

My bet is that sframe is using the system clock to eg poll file descriptors. If that's the case, you might just be forced to isolate the spots you fake the time. For example, I'm guessing this works as expected:
```
    def test_async(self):
        xyz.graph_function_example()
        with fake_time(fake_current_date):
            datetime.datetime.now()
```

That may or may not actually be useful in your situation, though.

**Comment by simon-weber** [comment]
I'm closing this as stale. Feel free to comment if this is still an issue and I'll reopen.
