### ISSUE TITLE
libfaketime is broken on OS X Sierra

### ISSUE THREAD

**Issue by canassa** [simon-weber/python-libfaketime#26]
Related to this:

https://github.com/wolfcw/libfaketime/issues/99

**Comment by simon-weber** [comment]
Thanks for the heads up. I'll watch that issue.

**Comment by simon-weber** [comment]
Whoops, I forgot to close this. It's fixed in 0.4.3 by https://github.com/simon-weber/python-libfaketime/pull/29.
