### ISSUE TITLE
Show a concrete example to enable profiling

### ISSUE THREAD

**Issue by ibizaman** [simon-weber/python-libfaketime#28]
I am using `pytest-profiling` which starts the profiler using
https://github.com/manahl/pytest-plugins/blob/master/pytest-profiling/pytest_profiling.py#L61.

Would you have an idea how to make pytest call `libfaketime`'s callbacks?

Even without taking into account `pytest-profiling`, how would you go about enabling `cProfile` at the correct time?

**Comment by simon-weber** [comment]
Sure thing. Here's what we use at Venmo for nose, but I'd imagine pytest has similar hooks:
```python
def disable_profiling_around_libfaketime(nose_config):
    """
    libfaketime's interception of time system calls will break profilers.

    If we detect that we're running under a profiler, we set up libfaketime callbacks to
    temporarily disable profiling when we're faking the time.
    """

    try:
        import nose_cprofile
    except ImportError:
        return

    profile_plugins = [p for p in nose_config.plugins.plugins if isinstance(p, nose_cprofile.Profile)]
    if not profile_plugins:
        return

    assert len(profile_plugins) == 1
    plugin = profile_plugins[0]
    if plugin.enabled:
        profiler = plugin.prof
        libfaketime.begin_callback = lambda _: profiler.disable()
        libfaketime.end_callback = lambda _: profiler.enable()
```

This gets called once from setup_package.

**Comment by ibizaman** [comment]
_aha_ thanks a lot!

**Comment by simon-weber** [comment]
Sure thing! If you've got a pytest example feel free to gist it, and I'll link both of these as examples from the readme.

**Comment by simon-weber** [comment]
Added in https://github.com/simon-weber/python-libfaketime/commit/c6738c22afa2c37cc29efd80e69dca270ce8753e.
