### ISSUE TITLE
Erases contents of LD_PRELOAD

### ISSUE THREAD

**Issue by adamchainz** [simon-weber/python-libfaketime#3]
I was just trying to improve my test suite runtime by using https://www.flamingspork.com/projects/libeatmydata/ - a similar `LD_PRELOAD` library for testing that avoids some filesystem operations. I found that `libfaketime`'s `reexec_if_needed()` replaces `LD_PRELOAD` rather than extending it, making it impossible to combine with using `libeatmydata`. It should really extend it with `:` separator if it is already set.

**Comment by simon-weber** [comment]
Good call; sorry about that.

**Comment by adamchainz** [comment]
Great :)

**Comment by simon-weber** [comment]
Better late than never!
