### ISSUE TITLE
time.time gives unexpected results

### ISSUE THREAD

**Issue by azmeuk** [simon-weber/python-libfaketime#37]
`time.time` does not seem to be mocked.
```python
import time, freezegun, libfaketime
with freezegun.freeze_time("1970-01-01 00:00:01"):
    print(time.time())
with libfaketime.fake_time("1970-01-01 00:00:01"):
    print(time.time())
```
```
1.0
1503929407.4042642
```

I think we could expect it to work.
```bash
$ env TZ=UTC faketime '1970-01-01 00:00:01' python -c "import time; print(time.time())"
```
```
1.765857203
```

**Comment by simon-weber** [comment]
Hm. Maybe we start with a failing test? I haven't tried to replicate it, but could be that it's version or system dependent.

**Comment by azmeuk** [comment]
Do you suggest I make a PR with a failing test (or maybe you want to do it)? That could be a start!

**Comment by simon-weber** [comment]
A PR wold be great. Otherwise I'm not sure when I'd get around to it, haha.

**Comment by azmeuk** [comment]
My bad, I forgot to run `libfaketime.reexec_if_needed()`.

**Comment by simon-weber** [comment]
Haha, no worries. I was gonna say, this would be a pretty bizarre bug.
