### ISSUE TITLE
Not work on Python 3.6.4

### ISSUE THREAD

**Issue by kyzima-spb** [simon-weber/python-libfaketime#42]
For some reason, your example does not work for Python 3.6.4 and Debian Buster =(
Does not pass the test, does not replace the time

**Comment by simon-weber** [comment]
My guess would be this is an issue upstream with https://github.com/wolfcw/libfaketime. Can you try building their newest version and seeing if it works without python-libfaketime? If it does, then I'll look into pulling in whatever changes are missing from [my fork](https://github.com/simon-weber/libfaketime).

**Comment by kyzima-spb** [comment]
I already compiled the latest version and checked it without Python. It work!

**Comment by simon-weber** [comment]
Hm. I looked over the changelog at https://github.com/simon-weber/libfaketime/compare/python-libfaketime...wolfcw:master and nothing stood out to me. Mostly it's just support for pthreads, which doesn't seem relevant.

Any ideas on how I might reproduce this?

**Comment by kyzima-spb** [comment]
I use Debian Buster (Testing release), python 3.6.4.
In a host system or a Docker container, I try to run the example, but nothing works, shows the actual date / time.
https://github.com/simon-weber/python-libfaketime#usage

Now I'm using the freezegun package. It works for me.
https://github.com/spulec/freezegun

**Comment by simon-weber** [comment]
My best guess is this was an issue with initialization. Feel free to reopen if you find out more.
