### ISSUE TITLE
Consider providing an easy way to configure DONT_FAKE_MONOTONIC env var

### ISSUE THREAD

**Issue by touilleMan** [simon-weber/python-libfaketime#45]
Unless setting the env var `DONT_FAKE_MONOTONIC`, by default, libfaketime also mock the monotonic clock.
However this can lead to really low level bugs given monotonic is often used by library (typically asynchronous framework such as asnycio or trio or profiling tools) where libfaketime is used to test user code.

I think there should a be at least a word about this behavior in the documentation.

However setting this env var from the code is complicated (especially when using the pytest-libfaketime module which automatically does the reloading really early on) and Python provide much higher level of abstraction than C so what is logical for one (opt in monotonic clock) becomes quite error prone for the other.

That's why I think the best would be to automatically enable this env var (still with documentation explaining this point) and providing a flag to allow user to manually enabling the mock of the monotonic clock if he really needs it:  `reexec_if_needed(mock_monotonic=False)`

I can work on a PR if you agree on this ;-)

**Comment by simon-weber** [comment]
Sounds reasonable to me. How likely do you think it is that people want to mock it? If it's very unlikely, then maybe we turn it off in the startup config and just give an option to turn it in `fake_time`?

**Comment by touilleMan** [comment]
As I said, from my point of view almost nobody use directly monotonic clocks, but the 3rd party library they rely on do !
I can talk about my own experience finding this issue: I got an internal error from the asynchronous framework trio on a random test working with asyncpg. It took me time to find out the issue (mostly by trying my test with freezegun), then I thought this was a logical limitation of python-libfaketime and was about to drop it (given there was no documentation about this), before reading the libfaketime documentation "just to be sure"...

That's why I think this stuff is just too low level for Python and should be turn on by default.

**Comment by simon-weber** [comment]
I decided to just turn it off without exposing it as an option. The stdlib doesn't seem to touch it and all the tests pass; if anybody notices we can add an option for it.

**Comment by touilleMan** [comment]
Sounds good to me ;-)
