### ISSUE TITLE
Timezone info is being ignored

### ISSUE THREAD

**Issue by pieterdd** [simon-weber/python-libfaketime#48]
I wrote the following test.

```python
from libfaketime import fake_time
from pytz import utc, timezone


def test_faketime():
    custom_timezone = timezone('Europe/Brussels')
    my_timestamp = custom_timezone.localize(datetime(2015, 2, 3))
    with fake_time(my_timestamp):
        assert datetime.utcnow() == datetime(2015, 2, 2, 23)
```

This fails because:

```
AssertionError: assert datetime.datetime(2015, 2, 3, 0, 0) == datetime.datetime(2015, 2, 2, 23, 0)
```

It only works correctly when I convert timestamps to UTC before faking the time:

```python
from libfaketime import fake_time
from pytz import utc, timezone


def test_faketime():
    custom_timezone = timezone('Europe/Brussels')
    my_timestamp = custom_timezone.localize(datetime(2015, 2, 3))
    with fake_time(my_timestamp.astimezone(utc)):
        assert datetime.utcnow() == datetime(2015, 2, 2, 23)
```

I'd expect libfaketime to always take timezone info into account and convert to UTC behind the scenes where needed. Is this a bug or expected behavior?

**Comment by simon-weber** [comment]
Outside of the tz_offset param, I don't think there's any handling of localized input. It doesn't sound like it'd be too hard to add by doing what you suggested, though.

**Comment by pieterdd** [comment]
I gave it a shot but found a problem during the implementation: https://github.com/simon-weber/python-libfaketime/commit/0c5c6580132611ac8570bdc1b9496874e6773f52

Is there an easy way to ensure that `datetime.now()` and `datetime.utcnow()` both behave correctly? For starters, neither should supply a `tzinfo` component to properly mock regular behavior. Secondly, their return value should be different (unless the system's default timezone is set to UTC).

**Comment by simon-weber** [comment]
Hm, yeah. What happens if we change the TZ env var to the input time zone [here](https://github.com/simon-weber/python-libfaketime/blob/58d03562be81509d49af786d19d02cc361b274f0/libfaketime/__init__.py#L151)? That might prevent converting into utc as well.

**Comment by pieterdd** [comment]
https://github.com/simon-weber/python-libfaketime/pull/49 should do the trick, closing in favor of that PR!
