### ISSUE TITLE
Tests hang with python 3.7

### ISSUE THREAD

**Issue by azmeuk** [simon-weber/python-libfaketime#51]
Tests indefinitely hangs when I add `py37` to `tox.ini` and launch `tox`, or when I directly launch tests with python 3.7 and pytest

**Comment by simon-weber** [comment]
Huh, I actually get a crash on linux. It looks like the private uuid function we're patching was renamed or removed.

**Comment by simon-weber** [comment]
Oh, whoops, that was actually coming from freezegun (https://github.com/spulec/freezegun/issues/225).

**Comment by simon-weber** [comment]
The same thing was causing the deadlock on our end.
