### ISSUE TITLE
Upgrade to libfaketime 0.9.10 to unbreak OSX Monterey support

### ISSUE THREAD

**Issue by saltmade** [simon-weber/python-libfaketime#63]
`libfaketime` recently [updated to 0.9.10](https://github.com/wolfcw/libfaketime/releases/tag/v0.9.10), partly to [fix an issue](https://github.com/wolfcw/libfaketime/issues/357) caused by upgrades to OSX Monterey. We're working around it currently using `freezegun`, but would prefer to drop that and keep on with `python-libfaketime`.

**Comment by simon-weber** [comment]
Thanks for the heads up; I'll look into it.

**Comment by simon-weber** [comment]
Unfortunately the merge diff against [my fork of libfaketime](https://github.com/wolfcw/libfaketime/compare/master...simon-weber:python-libfaketime) is [not straightforward](https://gist.github.com/simon-weber/0b823d1db258694c141cb3c88dc5e2a1), so it'll take some effort to get this done.

**Comment by saltdotac** [comment]
> Unfortunately the merge diff against [my fork of libfaketime](https://github.com/wolfcw/libfaketime/compare/master...simon-weber:python-libfaketime) is [not straightforward](https://gist.github.com/simon-weber/0b823d1db258694c141cb3c88dc5e2a1), so it'll take some effort to get this done.

Gotcha. Thank you for taking a look! I know we're not contributors, so we're happy to wait.
