### ISSUE TITLE
Support for subprocess

### ISSUE THREAD

**Issue by azmeuk** [simon-weber/python-libfaketime#66]
It seems running libfaketime and subprocess does not produce the expected results:

```python
import subprocess
from libfaketime import fake_time
from libfaketime import reexec_if_needed

reexec_if_needed()


with fake_time("2020-01-01 01:00:00"):
    process = subprocess.run("date", capture_output=True)
    print(process.stdout.decode())
```
```
Thu Apr  4 13:54:16 UTC 2024
```

I would love this to work though I am not sure this is even possible. If not, I think this worth mentioning it in the README.
What do you think?

**Comment by simon-weber** [comment]
Ah, ok. I was wrong -- this is on our end. I looked at the subprocess env and noticed that FAKETIME vars were there but not the preload vars. https://github.com/simon-weber/python-libfaketime/issues/18 described this problem and the fix (`reexec_if_needed(remove_vars=False)`) but the docs got lost in [a botched merge](https://github.com/simon-weber/python-libfaketime/commit/aa4a8c216596b2da0aff94aae8f97542ce8d8340).

**Comment by azmeuk** [comment]
Wow you traveled far back in time :)
Nice, `remove_vars=False` does the job. Thank you!
I think this would be nice to document this again. Do you want me to open a PR?
