### ISSUE TITLE
Support for `FAKETIME_TIMESTAMP_FILE`

### ISSUE THREAD

**Issue by azmeuk** [simon-weber/python-libfaketime#70]
libfaketime has a [FAKETIME_TIMESTAMP_FILE](https://github.com/wolfcw/libfaketime/blob/a04750217b8dc890ac584b92229d8c4a3f23c3e0/README#L217) parameter, that points to a file containing the time to mock:

The [README](https://github.com/wolfcw/libfaketime/blob/a04750217b8dc890ac584b92229d8c4a3f23c3e0/README#L424-L433) explains how this works:

> Changing the 'x' modifier during run-time
> -----------------------------------------
>
> Using FAKETIME_TIMESTAMP_FILE allows for easily changing the FAKETIME setting
while a program is running:
> ```
> echo "+0 x1" > /tmp/my-faketime.rc
> LD_PRELOAD=libfaketime.so.1 FAKETIME_TIMESTAMP_FILE="/tmp/my-faketime.rc" \
>  FAKETIME_NO_CACHE=1 ./some-program &
> sleep 10 ; echo "+0 x10" > /tmp/my-faketime.rc
> ```

I would love to be able to use this in python-libfaketime, so I could mock the time for a [python-slapd](https://github.com/python-ldap/python-slapd) server I run for tests, and dynamically change the mocked time while the server is running.

If this is OK with you, I would volunteer to provide a PR for this. I would love to hear your thoughts on the implementation though.

A simple version could look like this (the code is schematized, but you get the idea behind):

```python
time_ctx = time_context(timestamp_file="/tmp/my-faketime.rc")

with time_ctx.fake_time('1970-01-01 00:00:01'):
    server = AnyServer().run()


with time_ctx.fake_time('1980-01-01 00:00:01'):
    response = client.request(server.url, payload)
    assert response.payload.something == datetime(1980, 1, 1, 0, 0, 1)


with time_ctx.fake_time('1990-01-01 00:00:01'):
    response = client.request(server.url, payload)
    assert response.payload.something == datetime(1990, 1, 1, 0, 0, 1)
```

This introduces a new *context* object so several calls to `fake_time` will edit the same timestamp file, and impact all the processes that depends on it.

What do you think?

**Comment by simon-weber** [comment]
The main hurdle would be updating libfaketime. It looks like 0.9.8 added the timestamp file feature. python-libfaketime uses [a forked version](https://github.com/simon-weber/python-libfaketime/tree/master/libfaketime/vendor) of 0.9.7 with some [old changes](https://github.com/simon-weber/libfaketime/commits/d9d2bd76f00f95e9409e4a53d0469aef0e988a0b/?author=simon-weber) that I barely remember the context of.

Sierra is EOL now so at least that version could be removed. It might be easier to start over from the current version of libfaketime and reintroduce my old changes as needed rather than try to merge the two.

**Comment by azmeuk** [comment]
> It looks like 0.9.8 added the timestamp file feature.
Ah? I seems [FAKETIME_TIMESTAMP_FILE](https://github.com/simon-weber/libfaketime/blob/d9d2bd76f00f95e9409e4a53d0469aef0e988a0b/README#L175) is documented in your fork.

Anyways I suppose this would indeed be nice to have an up to date libfaketime version.

Do you remember what was the purpose of your changes? Was it the macOS support?

It looks like [GHA has support for macOS](https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images). We could start by adding GHA tests for macOS 12 to 14, and check if an updated libfaketime version without changes would pass the tests. If so, would that be enough for you?

**Comment by azmeuk** [comment]
Actually, [libfaketime itself is tested against macOS in GHA](https://github.com/wolfcw/libfaketime/blob/a04750217b8dc890ac584b92229d8c4a3f23c3e0/.github/workflows/make-test.yml#L15).

**Comment by azmeuk** [comment]
Hi @simon-weber
I would love to go forward with this issue but I feel I really miss understanding about the libfaketime forking/update thing.
Is this something you might tackle at some point? If not, could you please share the information you have on this (like, why the fork was needed in the first place) :pray: ?

**Comment by simon-weber** [comment]
[These linked changes](https://github.com/simon-weber/libfaketime/commits/d9d2bd76f00f95e9409e4a53d0469aef0e988a0b/?author=simon-weber) should be everything meaningful on the fork. I remember microsecond support being important. The other changes look mostly like removals to avoid having to update unneeded code.

**Comment by azmeuk** [comment]
#75 brings the libfaketime 0.9.10 update

**Comment by simon-weber** [comment]
Thanks for all your work to get this merged!
