### ISSUE TITLE
LD_PRELOAD cannot be preload (cannont open share object file)

### ISSUE THREAD

**Issue by toxinu** [simon-weber/python-libfaketime#8]
When starting my tests I have this message in output when calling `reexec_if_needed`:

``` bash
ERROR: ld.so: object '[..]/src/libfaketimepytest/libfaketime/vendor/libfaketime/src/libfaketime.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '[..]/src/libfaketimepytest/libfaketime/vendor/libfaketime/src/libfaketime.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

Everything were working like a charm yesterday. Tests still running but failed because datetimes are wrong.
I have already done: `pip install --force --ignore-installed libfaketime` in doubt, and problem still here.

How can I debug it?

**Comment by simon-weber** [comment]
Did you install the update yesterday? If so, my bet is that I messed up something with the packaging (I was on a new laptop).

Try doing `pip uninstall libfaketime; pip install libfaketime==0.1.1` and see if that fixes it.

**Comment by socketubs** [comment]
Just tried it and its fixed ! :+1: 
Thanks.

**Comment by simon-weber** [comment]
K, I'll use this issue to track the messed up release.

**Comment by simon-weber** [comment]
Huh, the new release works fine for me (on python 2). I'll wait to see if anyone else pops in here.

**Comment by socketubs** [comment]
I have only tested with `Python3.4`.

**Comment by simon-weber** [comment]
I'm guessing this is fixed now, and I had just messed up the packaging earlier.
